version: "3.8"

services:
  backend:
    build:
      args:
        - NODE_ENV=development
      context: backend
      target: development
    command: npm run dev
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=${TOKEN_SECRET}
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - ./backend:/app
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_PORT: ${PMA_PORT}
    networks:
      - public
      - private
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
